{
  "formatVersion": "1.1",
  "component": {
    "group": "br.com.brscan",
    "module": "brscan-sdk-documento-android",
    "version": "1.0.26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "brscan-sdk-documento-android-1.0.26.aar",
          "url": "brscan-sdk-documento-android-1.0.26.aar",
          "size": 292171,
          "sha512": "c523e6f18861b8e8c3d4b397411405b0481c698511b8440030432ca100af9ba455864f623cd3a00bfd414ea3a3c149817344fe64453ee0ecf2549591b36ba418",
          "sha256": "ee531488ce34551a00ff7fbca473fdfdfe526ae62c20928b87e0bcb2695aa7ee",
          "sha1": "29e706689744fd01925dd472fc6eb3ee0dfc783e",
          "md5": "05eac4a0745e0dbe8ba309f9af5e25bc"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "27.1-android"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.0.0-rc01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.0.0-rc01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.0.0-rc01"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.0.0-alpha20"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "playstore-dynamic-feature-support",
          "version": {
            "requires": "16.0.0-beta1"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "object-detection",
          "version": {
            "requires": "16.2.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "3.12.1"
          }
        },
        {
          "group": "com.jsibbold",
          "module": "zoomage",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "brscan-sdk-documento-android-1.0.26.aar",
          "url": "brscan-sdk-documento-android-1.0.26.aar",
          "size": 292171,
          "sha512": "c523e6f18861b8e8c3d4b397411405b0481c698511b8440030432ca100af9ba455864f623cd3a00bfd414ea3a3c149817344fe64453ee0ecf2549591b36ba418",
          "sha256": "ee531488ce34551a00ff7fbca473fdfdfe526ae62c20928b87e0bcb2695aa7ee",
          "sha1": "29e706689744fd01925dd472fc6eb3ee0dfc783e",
          "md5": "05eac4a0745e0dbe8ba309f9af5e25bc"
        }
      ]
    }
  ]
}
